aa: rand-m9-mstd0.5
batch_size: 128
decay_by_epoch: false
decay_epochs: 2.4
decay_rate: 0.97
drop: 0.2
epochs: 300
log_interval: 50
lr: 0.001
min_lr: 1.0e-07
model_ema: true
model_ema_decay: 0.9998
momentum: 0.9
opt: adamw
opt_betas: null
opt_eps: 0.001
remode: pixel
reprob: 0.2
sched: cosine
seed: 42
warmup_epochs: 3
warmup_lr: 1.0e-06
weight_decay: 1.0e-03
workers: 8
gen_images: true
