aa: rand-m9-mstd0.5
batch_size: 128
color_jitter: 0.0
decay_by_epoch: False
decay_epochs: 30
decay_rate: 0.1
drop: 0.25
epochs: 130
log_interval: 50
lr: 1.6
min_lr: 1.0e-05
model_ema: false
model_ema_decay: 0.9998
momentum: 0.9
smoothing: 0.1
opt: sgd
opt_betas: null
opt_eps: 1.0e-08
remode: const
reprob: 0.0
sched: cosine
seed: 42
warmup_epochs: 5
warmup_lr: 0.2
weight_decay: 1.0e-4
workers: 8
